name: Release

permissions:
  contents: write

on:
  release:
    types: ["published"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, windows]
        include:
          - platform: linux
            os: ubuntu-latest
            target_binary: ${{github.workspace}}/target/release/best_gizmo_setup_wizard
          - platform: windows
            os: windows-latest
            target_binary: ${{github.workspace}}/target/release/best_gizmo_setup_wizard.exe
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      if: ${{github.event_name == 'release'}}
      with:
        files:
          ${{ matrix.target_binary }}
