name: Release

permissions:
  contents: write

on:
  release:
    types: ["published"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Archive binary (Linux)
      run: tar -czf ${{ github.workspace }}/target/release/best_gizmo_setup_wizard_linux.tar.gz -C ${{ github.workspace }}/target/release/ best_gizmo_setup_wizard
    
    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      if: ${{github.event_name == 'release'}}
      with:
        files:
          ${{ github.workspace }}/target/release/best_gizmo_setup_wizard_linux.tar.gz


  build-and-upload-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Install Inno Setup
      run: |
        choco install innosetup -y
        refreshenv

    - name: Build Windows Installer
      run: .\installers\windows\build_installer.ps1
      working-directory: ./installers/windows

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      if: ${{github.event_name == 'release'}}
      with:
        files:
          ${{ github.workspace }}/target/release/best_gizmo_setup_wizard_windows_installer.exe
